# URLS TO DATA

test_chromosome: "chr20"

FILES:
  - chr20.full

SAMPLE_IDS:
  - m6401
  - m840
  
SEQUENCES:
  m6401:
  - m64012-190920-173625.Q20
  - m64012-190921-234837.Q20
  - m64015-190920-185703.Q20
  - m64015-190922-010918.Q20
  m840:
  - m84005-220827-014912-s1
  - m84011-220902-175841-s1
  - m84039-230418-213342-s3


regions:
  "1045":
    chromosome: "chr20"
    start: 10450000
    end: 10550000
  "1500":
    chromosome: "chr20"
    start: 15000000
    end: 16000000


# urls:
#   - url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.gbz"
#     output: "../resources/graph/hprc-v1.1-mc-chm13.gbz"
#   - url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-chm13/hprc-v1.1-mc-chm13.chroms/chr20.vg"
#     output: "../resources/graph/hprc-v1.1-mc-chm13-chr20.vg"
#   - url: "https://s3-us-west-2.amazonaws.com/human-pangenomics/working/HPRC_PLUS/HG002/raw_data/PacBio_HiFi/15kb/m64012_190920_173625.Q20.fastq"
#     output: "../resources/sequences/m64012_190920_173625.Q20.fastq"